### PR TITLE
add --debug to build system

### LINKED ISSUE #33: elm make with debug flag
It looks like from the settings file that you can turn the `--debug` flag on when doing a build:
https://github.com/elm-community/Elm.tmLanguage/blob/master/Settings/Elm%20Language%20Support.sublime-settings

However, turning it on doesn't seem to have an effect on the output js file. 

Is there a way to add flags to the build?

### PR DESCRIPTION
**Pull request by stoivo**
I change the color scheme since we should allow users to select. When we are using this theme we get this warning in the console.
```
Running elm-make /Users/simon/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/untitled.elm --output=/dev/null --report=json --yes
"Packages/Color Scheme - Default/Sunburst.tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"
```

fix #33

### CODE REVIEW

**Comment by stoivo** [comment]
@sentience ??

**Comment by sentience** [comment]
@stoivo Have you verified that compiler errors are still correctly highlighted with a user-selected color scheme? I agree with your intent, but I wonder if Sunburst was selected for a specific reason (e.g. maybe it includes highlighting for some scopes that most color schemes don't support?).

**Comment by stoivo** [comment]
I have not checked if the scoped we use are closely related to some specific scopes defined in Sunburst.  What I do know is that Sunburst is still the default. Sunburst will still be autoselected. But having it as a setting allows it to be changed by the user.

**Comment by stoivo** [comment]
What do you think?

**Comment by sentience** [comment]
Looks good! Thanks for clarifying.

**Comment by stoivo** [comment]
Thanks!

**Comment by stoivo** [comment]
New release?

**Comment by sentience** [comment]
@stoivo 👍 Release 0.22.0 is out now!

**Pull request merged**
