### PR TITLE
Prevent build command from crashing on Sublime 3/python 3

### PR DESCRIPTION
**Pull request by rtxm**
Tested in Sublime 3 on Linux only.

If someone can test on sublime 2 or on Windows to be sure, it would be perfect.

### CODE REVIEW

**Comment by rtxm** [comment]
This fixes #44 (for me at least).

**Comment by sentience** [comment]
Thanks @rtxm! We don't support Sublime 2 anymore, so all we need to do is test on Windows and macOS.

**Comment by Spaxe** [comment]
I tested @rtxm's changes and can confirm that it works on MacOS 10.12, Sublime Dev Build 3157.

However 725748f breaks it with the `b` buffer string - so I'm not sure if this is the right direction @sentience 

If you can undo the commit and merge from 0521d85 it will work on Macs.

**Comment by sentience** [comment]
@rtxm @Spaxe I merged and released this fix in 0.22.1 (without my erroneous conflict merge). Thanks!

**Pull request closed without merging**
